#!/usr/bin/env python3
"""Sensitivity of the coincidence budget to the two specification choices a
referee is entitled to question: the width of the null support, and the
distance convention.

Neither is a free parameter that was tuned. Both are declared in SPEC.md.
This script exists so that the sensitivity is measured and archived rather
than asserted.

  python3 robustness.py            full sweep, writes ROBUSTNESS.md
  python3 robustness.py --quick    fast configuration for CI
  python3 robustness.py --no-write compute and print only
"""
import argparse
import json
import sys

import numpy as np

from engine_p4 import (M_LO, SEED, TARGETS, TOL, W, clopper_pearson, near_any)

SPANS = [5.0, 5.602060, 6.0, 7.0, 8.0]  # decades; 5.602060 is the spec value


def sweep_span(decades, n, seed, batch=1_000_000):
    """Same null family, different support width. Q is homogeneous, so only
    the width matters: the lower endpoint is held and the upper one moves."""
    w = decades * np.log(10)
    rng = np.random.Generator(np.random.PCG64(seed))
    fixed = menu = drawn = 0
    while drawn < n:
        b = min(batch, n - drawn)
        m = np.exp(rng.uniform(np.log(M_LO), np.log(M_LO) + w, (b, 3)))
        q9 = 9.0 * m.sum(1) / np.sqrt(m).sum(1) ** 2
        fixed += int((np.abs(q9 - 8.0) <= TOL).sum())
        menu += int(near_any(q9, TARGETS, TOL).sum())
        drawn += b
    return fixed, menu, drawn


def sweep_metric(n, seed, batch=1_000_000):
    """Absolute vs relative distance. The spec uses absolute distance in 9Q,
    because Q is a bounded dimensionless coordinate and the phenomenological
    claim is additive proximity in Q. The relative-distance reading applies
    the observed fractional miss to every target instead."""
    rel = TOL / 8.0  # the observed fractional miss at the 8/9 target
    rng = np.random.Generator(np.random.PCG64(seed))
    abs_hits = rel_hits = drawn = 0
    while drawn < n:
        b = min(batch, n - drawn)
        m = np.exp(rng.uniform(np.log(M_LO), np.log(M_LO) + W, (b, 3)))
        q9 = 9.0 * m.sum(1) / np.sqrt(m).sum(1) ** 2
        abs_hits += int(near_any(q9, TARGETS, TOL).sum())
        hit = np.zeros(q9.shape, dtype=bool)
        for t in TARGETS:
            np.logical_or(hit, np.abs(q9 - t) <= rel * t, out=hit)
        rel_hits += int(hit.sum())
        drawn += b
    return abs_hits, rel_hits, drawn


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--no-write", action="store_true")
    a = ap.parse_args()
    n = 200_000 if a.quick else 10_000_000

    span_rows = []
    print(f"support sweep (N = {n:,} per row)")
    print(f"{'decades':>10} {'fixed 8/9':>12} {'menu':>12}")
    for d in SPANS:
        f, mh, dn = sweep_span(d, n, SEED)
        span_rows.append({"decades": d, "fixed_hits": f, "menu_hits": mh,
                          "n": dn, "f_fixed": f / dn, "f_menu": mh / dn})
        mark = "  <- spec" if abs(d - 5.602060) < 1e-6 else ""
        print(f"{d:>10.6f} {f / dn:>12.6f} {mh / dn:>12.6f}{mark}")

    ah, rh, dn = sweep_metric(n, SEED)
    metric = {"n": dn, "absolute_hits": ah, "relative_hits": rh,
              "f_absolute": ah / dn, "f_relative": rh / dn}
    print(f"\ndistance convention (N = {dn:,})")
    print(f"  absolute in 9Q, tol {TOL}        f = {ah / dn:.6f}   <- spec")
    print(f"  relative, fractional miss {TOL / 8.0:.6f}  f = {rh / dn:.6f}")

    payload = {"spans": span_rows, "metric": metric, "seed": SEED,
               "tolerance": TOL}
    if a.no_write or a.quick:
        return 0
    with open("robustness.json", "w") as fh:
        json.dump(payload, fh, indent=2)
        fh.write("\n")
    with open("ROBUSTNESS.md", "w") as fh:
        fh.write(render(payload))
    print("\nwrote robustness.json and ROBUSTNESS.md")
    return 0


def render(p):
    rows = "\n".join(
        f"| {r['decades']:.6f}{' **(spec)**' if abs(r['decades'] - 5.602060) < 1e-6 else ''} "
        f"| {r['f_fixed']:.6f} | {r['f_menu']:.6f} |"
        for r in p["spans"])
    m = p["metric"]
    cp_a = clopper_pearson(m["absolute_hits"], m["n"])
    cp_r = clopper_pearson(m["relative_hits"], m["n"])
    return f"""# Robustness of the single-claim coincidence budget

**Generated by `robustness.py`. Do not hand-edit.**

Two elements of the specification are matters of declared choice rather than
derivation: the width of the null support, and the distance convention. Both
are measured here so the sensitivity is on the record.

## Support width

The null draws three iid log-coordinates. Because Q is degree-zero
homogeneous, the endpoints 0.5 MeV and 2×10⁵ MeV carry no meaning
individually — only their logarithmic span does. The spec value is
5.602060 decades. For context, the observed y_t/y_u hierarchy at M_Z is
about 5.14 decades, so the spec support is neither absurdly broad nor
tuned to the observation.

| support (decades) | f, fixed 8/9 | f, menu |
|---|---|---|
{rows}

The menu reading is stable across this family. The fixed-target reading
moves by more, which is why the manuscript reports it as a
model-conditional frequency under a stated null and not as a universal
probability of accidental 8/9.

## Distance convention

| convention | hits | f | CP95 |
|---|---|---|---|
| absolute in 9Q, tol {p['tolerance']} **(spec)** | {m['absolute_hits']:,} | {m['f_absolute']:.6e} | [{cp_a[0]:.6e}, {cp_a[1]:.6e}] |
| relative, fractional miss {p['tolerance'] / 8.0:.6f} | {m['relative_hits']:,} | {m['f_relative']:.6e} | [{cp_r[0]:.6e}, {cp_r[1]:.6e}] |

The spec uses absolute distance because Q is a bounded, dimensionless
coordinate and the phenomenological claim is formulated as additive
proximity in Q. Applying the observed *fractional* miss to every target
instead is the natural alternative; it is reported here rather than left
for a referee to discover.

Seed {p['seed']}, derived from the spec SHA-256 (see `SPEC.md`).
"""


if __name__ == "__main__":
    sys.exit(main())
